cJSON:
	#curl -O https://raw.githubusercontent.com/DaveGamble/cJSON/v1.7.14/cJSON.c \
	#&& curl -O https://raw.githubusercontent.com/DaveGamble/cJSON/v1.7.14/cJSON.h

	curl -O https://gitee.com/mirrors/cJSON/raw/v1.7.14/cJSON.c \
	&& curl -O https://gitee.com/mirrors/cJSON/raw/v1.7.14/cJSON.h