# %W% %G%

# make and run all the example programs for
# lex & yacc, Second Edition
CFLAGES=-Wall -g
CC = gcc-13
LIBS = -ly -ll
LEX = flex
YACC = bison -y
CFLAGS = -DYYDEBUG=1



clean:
	- rm -rf *.o *.pgm *l.c *y.c *.tab.c *.tab.h
	- rm -rf ch1-02